@startuml isLeapYear
  title isLeapYear
  (*) --> "Gets user input"
  if "isGreaterThanOrEqualTo1582?" then
    --> [yes] if "isDivisibleBy100?" then
        --> [yes] if "isDivisibleBy400?" then
          -> [yes] ===A1===
          else
            ----> [no] "return false"
          endif
        else
          --> [no] ===A1===
            --> if "\nisDivisibleBy4?" then
            --> [yes] "return true"
            --> (*)
            else
              --> [no] "return false"
              --> (*)
            endif
        endif
  else
    -> [no] "throw ArgumentException"
  endif
@enduml
